export const ADD_NEW_AD_REQUEST = 'ADD_NEW_AD_REQUEST'
export const ADD_NEW_AD_SUCCESS = 'ADD_NEW_AD_SUCCESS'
export const ADD_NEW_AD_FAIL = 'ADD_NEW_AD_FAIL'

export const GET_ALL_ADS_REQUEST = 'GET_ALL_ADS_REQUEST'
export const GET_ALL_ADS_SUCCESS = 'GET_ALL_ADS_SUCCESS'
export const GET_ALL_ADS_FAIL = 'GET_ALL_ADS_FAIL'

export const EDIT_SINGLE_AD_REQUEST = 'EDIT_SINGLE_AD_REQUEST'
export const EDIT_SINGLE_AD_SUCCESS = 'EDIT_SINGLE_AD_SUCCESS'
export const EDIT_SINGLE_AD_FAIL = 'EDIT_SINGLE_AD_FAIL'
