export const GET_ALL_APPLICATIONS_REQUEST = 'GET_ALL_APPLICATIONS_REQUEST'
export const GET_ALL_APPLICATIONS_SUCCESS = 'GET_ALL_APPLICATIONS_SUCCESS' 
export const GET_ALL_APPLICATIONS_FAIL = 'GET_ALL_APPLICATIONS_FAIL' 
