export const GET_All_CATEGORIES_REQUEST = 'GET_All_CATEGORIES_REQUEST'
export const GET_All_CATEGORIES_SUCCESS = 'GET_All_CATEGORIES_SUCCESS'
export const GET_All_CATEGORIES_FAIL = 'GET_All_CATEGORIES_FAIL'

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS' 
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL' 


export const GET_All_SUBCATEGORIES_OF_PARENT_REQUEST = 'GET_All_SUBCATEGORIES_OF_PARENT_REQUEST'
export const GET_All_SUBCATEGORIES_OF_PARENT_SUCCESS = 'GET_All_SUBCATEGORIES_OF_PARENT_SUCCESS'
export const GET_All_SUBCATEGORIES_OF_PARENT_FAIL = 'GET_All_SUBCATEGORIES_OF_PARENT_FAIL'
