export const GET_All_CATEGORIES_REQUEST = 'GET_All_CATEGORIES_REQUEST'
export const GET_All_CATEGORIES_SUCCESS = 'GET_All_CATEGORIES_SUCCESS'
export const GET_All_CATEGORIES_FAIL = 'GET_All_CATEGORIES_FAIL'
