export const OPEN_CHAT = 'OPEN_CHAT'
export const CLOSE_CHAT = 'CLOSE_CHAT'

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'

export const GET_ALL_MESSAGES_REQUEST = 'GET_ALL_MESSAGES_REQUEST'
export const GET_ALL_MESSAGES_SUCCESS = 'GET_ALL_MESSAGES_SUCCESS'
export const GET_ALL_MESSAGES_FAIL = 'GET_ALL_MESSAGES_FAIL'

export const GET_ALL_CHAT_USERS_REQUEST = 'GET_ALL_CHAT_USERS_REQUEST'
export const GET_ALL_CHAT_USERS_SUCCESS = 'GET_ALL_CHAT_USERS_SUCCESS'
export const GET_ALL_CHAT_USERS_FAIL = 'GET_ALL_CHAT_USERS_FAIL'