export const GET_FEATURED_PRODUCTS_REQUEST = 'GET_FEATURED_PRODUCTS_REQUEST'
export const GET_FEATURED_PRODUCTS_SUCCESS = 'GET_FEATURED_PRODUCTS_SUCCESS'
export const GET_FEATURED_PRODUCTS_FAIL = 'GET_FEATURED_PRODUCTS_FAIL'
