export const GET_SUBCATEGORIES_REQUEST = 'GET_SUBCATEGORIES_REQUEST'
export const GET_SUBCATEGORIES_SUCCESS = 'GET_SUBCATEGORIES_SUCCESS'
export const GET_SUBCATEGORIES_FAIL = 'GET_SUBCATEGORIES_FAIL'
