export const GET_SUBCATEGORIES_REQUEST = 'GET_SUBCATEGORIES_REQUEST'
export const GET_SUBCATEGORIES_SUCCESS = 'GET_SUBCATEGORIES_SUCCESS'
export const GET_SUBCATEGORIES_FAIL = 'GET_SUBCATEGORIES_FAIL'

export const CREATE_SUBCATEGORY_REQUEST = 'CREATE_SUBCATEGORY_REQUEST'
export const CREATE_SUBCATEGORY_SUCCESS = 'CREATE_SUBCATEGORY_SUCCESS'
export const CREATE_SUBCATEGORY_FAIL = 'CREATE_SUBCATEGORY_FAIL'

