export  const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST'
export  const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS'
export  const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL'

export const GET_ALL_STORE_REVIEWS_REQUEST = 'GET_ALL_STORE_REVIEWS_REQUEST'
export const GET_ALL_STORE_REVIEWS_SUCCESS = 'GET_ALL_STORE_REVIEWS_SUCCESS'
export const GET_ALL_STORE_REVIEWS_FAIL = 'GET_ALL_STORE_REVIEWS_FAIL'

