export const GET_ALL_SPECIAL_PRODUCTS_REQUEST = 'GET_ALL_SPECIAL_PRODUCTS_REQUEST'
export const GET_ALL_SPECIAL_PRODUCTS_SUCCESS = 'GET_ALL_SPECIAL_PRODUCTS_SUCCESS' 
export const GET_ALL_SPECIAL_PRODUCTS_FAIL = 'GET_ALL_SPECIAL_PRODUCTS_FAIL' 
