export const GET_STORE_PRODUCTS_REQUEST= 'GET_STORE_PRODUCTS_REQUEST'
export const GET_STORE_PRODUCTS_SUCCESS= 'GET_STORE_PRODUCTS_SUCCESS'
export const GET_STORE_PRODUCTS_FAIL= 'GET_STORE_PRODUCTS_FAIL'

export const GET_SINGLE_STORE_INFO_REQUEST =' GET_SINGLE_STORE_INFO_REQUEST'
export const GET_SINGLE_STORE_INFO_SUCCESS =' GET_SINGLE_STORE_INFO_SUCCESS'
export const GET_SINGLE_STORE_INFO_FAIL =' GET_SINGLE_STORE_INFO_FAIL'

