export const GET_STORE_PRODUCTS_REQUEST= 'GET_STORE_PRODUCTS_REQUEST'
export const GET_STORE_PRODUCTS_SUCCESS= 'GET_STORE_PRODUCTS_SUCCESS'
export const GET_STORE_PRODUCTS_FAIL= 'GET_STORE_PRODUCTS_FAIL'
