export const EDIT_SINGLE_USER_REQUEST = 'EDIT_SINGLE_USER_REQUEST'
export const EDIT_SINGLE_USER_SUCCESS = 'EDIT_SINGLE_USER_SUCCESS'
export const EDIT_SINGLE_USER_FAIL = 'EDIT_SINGLE_USER_FAIL'

export const GET_ALL_USERS_REQUEST = ' GET_ALL_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = ' GET_ALL_USERS_SUCCESS' 
export const GET_ALL_USERS_FAIL = ' GET_ALL_USERS_FAIL' 
